import {chromium} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const base=process.env.RESON_URL||'http://127.0.0.1:5514/',out=process.env.RESON_MOTION||'../evidence/motion';await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.platform==='win32'?{executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}:{})}),records=[];
for(const [name,width,height] of [['desktop',1440,1000],['mobile',390,844]]){
 const context=await browser.newContext({viewport:{width,height},hasTouch:name==='mobile',recordVideo:{dir:out,size:{width,height}}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.waitForFunction(()=>window.__RESON?.state().studio.webgl);await page.evaluate(()=>document.fonts.ready);
 const shots=[];
 for(const p of [0,.15,.32,.55,.75,.9,1,.9,.75,.55,.32,.15,0]){await page.evaluate(p=>{const s=window.__RESON.state();window.scrollTo({top:s.scroll.start+s.scroll.range*p,behavior:'instant'});},p);await page.waitForTimeout(300);const path=`${out}/${name}-${shots.length}.png`;await page.screenshot({path});shots.push({p,file:path});}
 const frames=await page.evaluate(async()=>{const frames=[];async function sweep(from,to,duration){const start=performance.now();return new Promise(resolve=>{function tick(now){const t=Math.min(1,(now-start)/duration),s=window.__RESON.state();window.scrollTo({top:s.scroll.start+s.scroll.range*(from+(to-from)*t),behavior:'instant'});frames.push({time:now-start,direction:from<to?'forward':'reverse',progress:s.progress,amount:s.anatomy.amount,...s.anatomy});if(t<1)requestAnimationFrame(tick);else resolve();}requestAnimationFrame(tick);});}await sweep(0,1,8000);await sweep(1,0,8000);return frames;});
 await page.evaluate(()=>{const s=window.__RESON.state();window.scrollTo({top:s.scroll.start+s.scroll.range*.6,behavior:'instant'});});await page.waitForTimeout(200);await page.setViewportSize({width:height,height:width});await page.waitForTimeout(400);await page.setViewportSize({width,height});await page.waitForTimeout(400);await page.evaluate(()=>{const s=window.__RESON.state();window.scrollTo({top:s.scroll.start+s.scroll.range*.35,behavior:'instant'});});await page.waitForTimeout(300);
 for(const f of frames){assert.ok(f.bounds.left>=1&&f.bounds.right<=f.width-1);assert.ok(f.bounds.top>=1&&f.bounds.bottom<=f.height-1);assert.ok(f.amount>=0&&f.amount<=1);}
 const intervals=frames.slice(1).map((f,i)=>f.direction===frames[i].direction?f.time-frames[i].time:0).filter(x=>x>0);const sorted=intervals.toSorted((a,b)=>a-b);const video=page.video();await context.close();const file=`${out}/${name}-forward-reverse.webm`;await video.saveAs(file);await video.delete();assert.deepEqual(errors,[]);const record={name,frames:frames.length,averageFrameMs:intervals.reduce((a,b)=>a+b,0)/intervals.length,p95FrameMs:sorted[Math.floor(sorted.length*.95)],maxFrameMs:Math.max(...intervals),errors:0,video:file};records.push(record);await writeFile(`${out}/${name}-telemetry.json`,JSON.stringify(frames));await writeFile(`${out}/${name}-shots.json`,JSON.stringify(shots));console.log(JSON.stringify(record));
}
await writeFile(`${out}/manifest.json`,JSON.stringify({base,records},null,2));await browser.close();
