import {chromium} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const base=process.env.RESON_URL||'http://127.0.0.1:5514/',out=process.env.RESON_EVIDENCE||'../evidence/browser';await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.platform==='win32'?{executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}:{})});
const records=[];
const state=page=>page.evaluate(()=>window.__RESON.state());
async function ready(page,url){await page.goto(url);await page.waitForFunction(()=>!!window.__RESON);await page.waitForFunction(()=>{const v=window.__RESON.state().studio;return !v.webgl||v.renderedAmount===v.amount;});await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(180);}
{
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true}),page=await context.newPage();await context.addInitScript(()=>{Object.defineProperty(window.HTMLDialogElement.prototype,'onclose',{configurable:true,set(handler){this.addEventListener('close',event=>setTimeout(()=>handler.call(this,event),500));}});const read=window.File.prototype.text;window.File.prototype.text=async function(){if(this.name==='slow.json')await new Promise(resolve=>setTimeout(resolve,450));return read.call(this);};});await ready(page,base);await page.locator('#design-name').fill('<img src=x onerror=alert(1)>');await page.locator('#save').click();await page.locator('#design-name').fill('<img src=x onerror=alert(1)>');await page.locator('#save').click();assert.equal((await state(page)).designs.length,1);assert.equal(await page.locator('.saved-info h3 img').count(),0);
 const bads=['{',JSON.stringify({version:1,current:{...(await state(page)).current,width:999},designs:[]}),JSON.stringify({version:1,current:(await state(page)).current,designs:[{name:'A',config:(await state(page)).current},{name:'a',config:(await state(page)).current}]})];
 for(const text of bads){await page.locator('#import-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(text)});assert.equal(await page.locator('#import-dialog').evaluate(d=>d.open),false);assert.equal((await state(page)).designs.length,1);}
 const document={version:1,current:{...(await state(page)).current,finish:'ink'},designs:[{name:'Imported ink',config:{...(await state(page)).current,finish:'ink'}}]};
 await page.locator('#import-file').setInputFiles({name:'slow.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...document,designs:[{name:'Stale import',config:document.current}]}))});await page.locator('#import-file').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(document))});await page.waitForFunction(()=>document.querySelector('#import-dialog').open);await page.waitForTimeout(500);assert.ok((await page.locator('#import-summary').textContent()).includes('Imported ink'));assert.ok(!(await page.locator('#import-summary').textContent()).includes('Stale import'));await page.locator('#import-dialog button[value="cancel"]').click();
 await page.locator('#import-file').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(document))});await page.locator('#import-dialog button[value="cancel"]').click();assert.equal((await state(page)).current.finish,'walnut');await page.locator('#import-file').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(document))});await page.locator('#replace').click();assert.equal((await state(page)).designs[0].name,'Imported ink');await page.locator('#undo').click();assert.equal((await state(page)).designs[0].name,'<img src=x onerror=alert(1)>');
 for(let i=1;i<6;i++){await page.locator('#design-name').fill(`Alternative ${i}`);await page.locator('#save').click();}assert.equal((await state(page)).designs.length,6);assert.equal(await page.locator('#save').isDisabled(),true);await page.reload();await page.waitForFunction(()=>window.__RESON?.state().designs.length===6);await page.locator('[data-remove]').nth(0).click();await page.keyboard.press('Escape');assert.equal((await state(page)).designs.length,6);await page.locator('[data-remove]').nth(0).click();await page.locator('#confirm-remove').click();assert.equal((await state(page)).designs.length,5);await page.locator('#undo').click();assert.equal((await state(page)).designs.length,6);
 const downloadPromise=page.waitForEvent('download');await page.locator('#export').click();const download=await downloadPromise;await download.saveAs(`${out}/export.json`);assert.equal(download.suggestedFilename(),'reson-designs.json');
 await page.locator('#studio-visual').focus();const yawBefore=await page.locator('canvas').first().screenshot();await page.keyboard.press('ArrowRight');await page.waitForTimeout(400);assert.notDeepEqual(yawBefore,await page.locator('canvas').first().screenshot());
 for(const l of ['ru','kk','en']){await page.locator(`[data-locale="${l}"]`).click();assert.equal((await state(page)).locale,l);assert.equal((await state(page)).designs.length,6);}
 await page.evaluate(()=>{const s=window.__RESON.state();scrollTo({top:s.scroll.start+s.scroll.range*.55,behavior:'instant'});});await page.waitForTimeout(200);await page.setViewportSize({width:844,height:390});await page.waitForTimeout(250);await page.setViewportSize({width:390,height:844});await page.waitForTimeout(250);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await page.locator('#studio').scrollIntoViewIfNeeded();const cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:180,y:650}]});for(let i=1;i<=8;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:180,y:650-i*35}]});await page.waitForTimeout(20);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();assert.ok(await page.evaluate(()=>scrollY>0));await context.close();records.push({name:'interrupted-and-repeat-workflows',passed:true});console.log('Interrupted/repeated dialogs, delayed close events and stale file reads: passed');
}
if(!process.env.RESON_SKIP_REGULAR)for(const [name,width,height,lang] of [['desktop',1440,1000,'en'],['laptop',1280,800,'en'],['tablet',768,1024,'ru'],['mobile',390,844,'en'],['small-mobile',320,568,'en'],['mobile-ru',390,844,'ru'],['mobile-kk',390,844,'kk'],['small-kk',320,568,'kk'],['small-ru',320,568,'ru'],['landscape',844,390,'en']]){
 const context=await browser.newContext({viewport:{width,height},hasTouch:name.includes('mobile'),isMobile:name.includes('mobile')}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await ready(page,`${base}?lang=${lang}`);assert.equal((await state(page)).studio.webgl,true);assert.equal((await state(page)).locale,lang);await page.screenshot({path:`${out}/${name}-studio.png`});
 const checks=[];
 for(const p of [0,.1,.22,.32,.47,.64,.73,.87,1,.87,.64,.32,0]){
  await page.evaluate(p=>{const s=window.__RESON.state();scrollTo({top:s.scroll.start+s.scroll.range*p,behavior:'instant'});},p);await page.waitForFunction(p=>{const s=window.__RESON.state();return Math.abs(s.progress-p)<.005&&Math.abs(s.anatomy.renderedAmount-s.anatomy.amount)<.000001;},p,{timeout:15000});const s=await state(page),b=s.anatomy.bounds;assert.ok(Math.abs(s.progress-p)<.005,`${name}: progress ${p}`);assert.ok(b.left>=2&&b.right<=s.anatomy.width-2,`${name} ${p}: horizontal model clipping`);assert.ok(b.top>=2&&b.bottom<=s.anatomy.height-2,`${name} ${p}: vertical model clipping`);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${name}: overflow`);assert.ok(await page.evaluate(()=>{const s=window.__RESON.state(),host=document.querySelector('#anatomy-visual').getBoundingClientRect(),b=s.anatomy.bounds;return [...document.querySelectorAll('.anatomy-caption h3,.anatomy-caption p')].every(el=>{const r=el.getBoundingClientRect();return Math.min(r.right,host.left+b.right)-Math.max(r.left,host.left+b.left)<=0||Math.min(r.bottom,host.top+b.bottom)-Math.max(r.top,host.top+b.top)<=0;});}),`${name}: caption overlaps geometry`);checks.push({p,bounds:b,calls:s.anatomy.calls,triangles:s.anatomy.triangles});if([.32,.64,1].includes(p))await page.screenshot({path:`${out}/${name}-construction-${p}.png`});
 }
 await page.locator('[data-field="finish"][data-option="oak"]').click();assert.equal((await state(page)).current.finish,'oak');await page.locator('#undo').click();assert.equal((await state(page)).current.finish,'walnut');await page.locator('[data-field="shape"][data-option="tall"]').click();await page.locator('[data-field="grille"][data-option="slats"]').click();await page.locator('[data-field="base"][data-option="plinth"]').click();await page.locator('#width').fill('300');await page.locator('#width').dispatchEvent('change');await page.locator('#depth').fill('340');await page.locator('#depth').dispatchEvent('change');await page.locator('[data-view="3.14"]').click();await page.waitForTimeout(650);await page.locator('#reset').click();assert.equal((await state(page)).current.shape,'compact');
 await page.locator('#design-name').fill('Evening walnut');await page.locator('#save').click();await page.locator('[data-field="finish"][data-option="oak"]').click();await page.locator('#design-name').fill('Morning oak');await page.locator('#save').click();assert.equal((await state(page)).designs.length,2);await page.locator('[data-compare]').nth(0).click();await page.locator('[data-compare]').nth(1).click();assert.equal(await page.locator('.compare-pair figure').count(),2);assert.equal(await page.locator('.different').count(),1);await page.screenshot({path:`${out}/${name}-compare.png`});
 const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa']).analyze();assert.deepEqual(axe.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)})),[],`${name}: accessibility`);
 await page.reload();await page.waitForFunction(()=>window.__RESON?.state().designs.length===2);assert.equal((await state(page)).current.finish,'oak');assert.ok((await state(page)).designs.every(d=>d.hasImage));assert.deepEqual(errors,[]);records.push({name,width,height,lang,checks,axeViolations:0,errors:0});await context.close();console.log(`${name}: 3D construction, controls, saved designs, comparison, reload and accessibility passed`);
}
for(const [name,url,reduced] of [['fallback',`${base}?fallback=1&lang=kk`,false],['reduced-motion',base,true],['storage-blocked',base,false],['text-200',`${base}?lang=ru`,false]]){
 const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:reduced?'reduce':'no-preference'});if(name==='storage-blocked')await context.addInitScript(()=>{Storage.prototype.setItem=function(){throw new DOMException('blocked','QuotaExceededError');};});const page=await context.newPage();await ready(page,url);if(name==='fallback')assert.equal((await state(page)).studio.webgl,false);if(reduced){assert.equal((await state(page)).motion,false);await page.locator('#explore').fill('100');await page.locator('#explore').dispatchEvent('input');assert.equal((await state(page)).anatomy.amount,1);}if(name==='text-200'){await page.addStyleTag({content:'html{font-size:200%}'});await page.waitForFunction(()=>document.documentElement.classList.contains('text-enlarged'));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'200% text overflow');}else{await page.locator('#design-name').fill('Available');await page.locator('#save').click();assert.equal((await state(page)).designs.length,1);if(name==='storage-blocked')assert.ok((await page.locator('#status').textContent()).includes('storage'));}
 await page.screenshot({path:`${out}/${name}.png`,fullPage:name==='text-200'});const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa']).analyze();assert.equal(axe.violations.length,0,JSON.stringify(axe.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))));await context.close();records.push({name,passed:true});console.log(`${name}: passed`);
}
await writeFile(`${out}/report.json`,JSON.stringify({base,records},null,2));await browser.close();
