import '@fontsource-variable/inter';
import './style.css';
import { defaults,validateConfig,parseDocument,exportDocument,cleanName,equal,height,explosion,type Config,type Saved,type Document } from './config.ts';
import { copy,languages,type Locale } from './copy.ts';
import { Viewer,tones } from './model.ts';
const key='reson-collection-v1';
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const q=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
let current={...defaults},designs:Saved[]=[],locale:Locale='en',recovered=false;
try{const lang=new URLSearchParams(location.search).get('lang')||localStorage.getItem('reson-language');if(languages.includes(lang as Locale))locale=lang as Locale;const raw=localStorage.getItem(key);if(raw){if(raw.length>800000)throw Error('size');const stored=JSON.parse(raw);const doc=parseDocument(JSON.stringify({version:stored.version,current:stored.current,designs:stored.designs.map((d:Saved)=>({name:d.name,config:d.config}))}));current=doc.current;designs=doc.designs;designs.forEach((d,i)=>{const image=stored.designs[i].image;if(typeof image==='string'&&/^data:image\/webp;base64,[A-Za-z0-9+/]+=*$/.test(image)&&image.length<120000)d.image=image;});}}catch{recovered=true;}
const undo:{current:Config;designs:Saved[]}[]=[];
let studio:Viewer,anatomy:Viewer,selected:string[]=[],pending:Document|null=null,removeId:string|null=null,rangeStart:Config|null=null,importVersion=0;
const media=matchMedia('(prefers-reduced-motion: reduce)');let motion=!media.matches;
let scrollFrame=0,progress=0,manualAmount=0;
function snapshot(){undo.push({current:{...current},designs:designs.map(d=>({...d,config:{...d.config}}))});if(undo.length>30)undo.shift();}
function status(message:string,error=false){const el=q('#status');el.textContent=message;el.classList.toggle('error',error);}
function persist(){try{localStorage.setItem(key,JSON.stringify({version:1,current,designs}));return true;}catch{status(copy[locale].storageError,true);return false;}}
function update(config:Config,record=true){config=validateConfig(config);if(equal(config,current))return;if(record)snapshot();current=config;studio.setConfig(current);anatomy.setConfig(current);sync();persist();}
function sync(){const c=copy[locale];document.querySelectorAll<HTMLButtonElement>('[data-option]').forEach(button=>{const field=button.dataset.field as keyof Config;button.setAttribute('aria-pressed',String(current[field]===button.dataset.option));});for(const field of ['width','depth'] as const){q<HTMLInputElement>(`#${field}`).value=String(current[field]);q(`#${field}-value`).textContent=`${current[field]} ${c.mm}`;}
  q('#dimension-value').textContent=`${current.width} × ${height(current)} × ${current.depth} ${c.mm}`;q<HTMLButtonElement>('#undo').disabled=!undo.length;q<HTMLButtonElement>('#save').disabled=designs.length>=6;q('#finish-value').textContent=`${c[current.finish]} / ${c[current.metal]}`;
  q('#studio-visual').style.setProperty('--finish',tones[current.finish]);q('#studio-visual').dataset.finish=current.finish;
}
function options(field:keyof Config,label:string,values:string[]){const c=copy[locale];return `<fieldset><legend>${label}</legend><div class="options ${field==='finish'||field==='metal'?'swatches':''}">${values.map(v=>`<button type="button" data-field="${field}" data-option="${v}" aria-pressed="${current[field]===v}">${field==='finish'||field==='metal'?`<span class="swatch ${v}" aria-hidden="true"></span>`:''}${c[v as keyof typeof c]}</button>`).join('')}</div></fieldset>`;}
function dimensions(config:Config){return `${config.width} × ${height(config)} × ${config.depth} ${copy[locale].mm}`;}
function thumb(d:Saved){return d.image?`<img src="${d.image}" alt="${escape(d.name)}" width="360" height="300">`:`<div class="material-preview" style="--finish:${tones[d.config.finish]}"><span>${copy[locale][d.config.finish]}</span><small>${copy[locale][d.config.metal]}</small></div>`;}
function renderSaved(){const c=copy[locale];selected=selected.filter(id=>designs.some(d=>d.id===id));q('#saved-grid').innerHTML=designs.length?designs.map(d=>`<article class="saved-card">${thumb(d)}<div class="saved-info"><h3>${escape(d.name)}</h3><p>${c[d.config.finish]} · ${c[d.config.shape]}</p><p class="mono">${dimensions(d.config)}</p><div class="saved-actions"><button data-load="${d.id}">${c.load}</button><button data-compare="${d.id}" aria-pressed="${selected.includes(d.id)}">${c.compare}</button><button class="remove" data-remove="${d.id}" aria-label="${c.remove}: ${escape(d.name)}">×</button></div></div></article>`).join(''):`<div class="empty"><span class="empty-symbol" aria-hidden="true">◎</span><h3>${c.empty}</h3><p>${c.emptyText}</p><a href="#studio">${c.studio}</a></div>`;
  renderCompare();sync();
}
function renderCompare(){const c=copy[locale],a=designs.find(d=>d.id===selected[0]),b=designs.find(d=>d.id===selected[1]);q('#compare-count').textContent=`${selected.length} / 2`;q<HTMLButtonElement>('#clear-compare').hidden=!selected.length;
  q('#comparison').innerHTML=a&&b?`<div class="compare-pair">${[a,b].map(d=>`<figure>${thumb(d)}<figcaption>${escape(d.name)}</figcaption></figure>`).join('')}</div><table><caption class="sr-only">${c.compare}</caption><thead><tr><th scope="col">${c.design}</th><th scope="col">${escape(a.name)}</th><th scope="col">${escape(b.name)}</th></tr></thead><tbody>${(['shape','finish','metal','grille','base'] as const).map(field=>`<tr class="${a.config[field]!==b.config[field]?'different':''}"><th scope="row">${{shape:c.cabinet,finish:c.finish,metal:c.metal,grille:c.front,base:c.base}[field]}</th><td>${c[a.config[field]]}</td><td>${c[b.config[field]]}</td></tr>`).join('')}<tr class="${dimensions(a.config)!==dimensions(b.config)?'different':''}"><th scope="row">${c.dimensions}</th><td>${dimensions(a.config)}</td><td>${dimensions(b.config)}</td></tr></tbody></table>`:`<p class="comparison-hint">${c.compareHint}${a?` <strong>${escape(a.name)}</strong>`:''}</p>`;
}
function render(){const c=copy[locale];document.documentElement.lang=locale;document.title=`RESON — ${c.eyebrow.toLowerCase()}`;
  q('#app').innerHTML=`<a class="skip" href="#studio">${c.skip}</a><header class="header"><a class="brand" href="#studio" aria-label="RESON">RESON<span class="brand-dot" aria-hidden="true">◎</span></a><nav aria-label="${c.studio}"><a href="#studio">${c.studio}</a><a href="#construction">${c.construction}</a><a href="#collection">${c.collection}</a></nav><div class="languages" role="group" aria-label="${c.language}">${languages.map(l=>`<button data-locale="${l}" aria-pressed="${locale===l}" lang="${l}" aria-label="${{en:'English',ru:'Русский',kk:'Қазақша'}[l]}">${l.toUpperCase()}</button>`).join('')}</div></header>
  <main><section id="studio" class="studio section"><div class="studio-title"><div><p class="eyebrow">${c.eyebrow}</p><h1>${c.heading.replace('\n',' <br>')}</h1></div><p class="intro">${c.intro}</p></div><div class="workbench"><div class="visual-wrap"><div class="visual-head"><span class="mono">${c.model}</span><span class="view-mark" aria-hidden="true">01 / 03</span></div><div id="studio-visual" class="visual" tabindex="0" role="group" aria-label="${c.orbit}" aria-describedby="rotate-hint"><img class="fallback-image" src="./stills/speaker.webp" alt="RESON R—01"><p class="fallback-message">${c.fallback}</p><span class="stage-shadow" aria-hidden="true"></span></div><div class="visual-foot"><span id="finish-value"></span><span class="mono" id="dimension-value"></span></div><div class="view-tools"><div class="view-buttons"><button data-view="0" aria-label="${c.frontView}">01</button><button data-view="-.4" aria-label="${c.angleView}" aria-pressed="true">02</button><button data-view="3.14" aria-label="${c.rearView}">03</button></div><p id="rotate-hint">${c.rotate}</p><button id="motion" aria-pressed="${motion}">${c.motion}: ${motion?c.motionOn:c.motionOff}</button></div></div>
  <aside class="controls" aria-label="${c.design}"><div class="controls-title"><h2>${c.design}</h2><span class="mono">R—01</span></div>${options('shape',c.cabinet,['compact','tall'])}${options('finish',c.finish,['walnut','oak','ink'])}${options('metal',c.metal,['copper','silver','graphite'])}${options('grille',c.front,['open','slats'])}${options('base',c.base,['feet','plinth'])}<div class="ranges">${(['width','depth'] as const).map(field=>`<label for="${field}">${c[field]}<output id="${field}-value" for="${field}"></output></label><input id="${field}" type="range" min="${field==='width'?210:230}" max="${field==='width'?300:340}" step="10" value="${current[field]}">`).join('')}</div><div class="history-tools"><button id="undo">${c.undo}</button><button id="reset">${c.reset}</button></div><form id="save-form"><label for="design-name">${c.name}</label><div class="save-row"><input id="design-name" maxlength="40" required placeholder="${c.namePlaceholder}"><button class="primary" id="save">${c.save}<span aria-hidden="true">+</span></button></div><p>${c.saveHint}</p></form></aside></div><p id="status" role="status" aria-live="polite"></p><div class="studio-bottom"><p>${c.note}</p><a class="text-link" href="#construction">${c.scroll}<span aria-hidden="true">↓</span></a></div></section>
  <section id="construction" class="construction"><div class="anatomy-intro section"><p class="eyebrow">${c.anatomyLabel}</p><h2>${c.anatomyTitle.replace('\n','<br>')}</h2><p>${c.anatomyIntro}</p></div><div id="scroll-study" class="scroll-study"><div class="anatomy-sticky"><div class="anatomy-caption"><span class="chapter-number mono">01 / 04</span><h3 id="chapter-title">${c.chapters[0]}</h3><p id="chapter-text">${c.chapterText[0]}</p></div><div id="anatomy-visual" class="anatomy-visual"><img class="fallback-image" src="./stills/speaker.webp" alt="RESON R—01"><p class="fallback-message">${c.fallback}</p></div><div class="chapter-controls"><div class="chapter-buttons" role="group" aria-label="${c.construction}">${c.chapters.map((s,i)=>`<button data-chapter="${i}" aria-label="${s}" aria-pressed="${i===0}">0${i+1}</button>`).join('')}</div><div class="manual"><label for="explore">${c.manual}</label><input id="explore" type="range" min="0" max="100" value="0"><span>${c.assembled} / ${c.separated}</span></div><span class="scroll-line" aria-hidden="true"><i></i></span></div></div></div></section>
  <section id="collection" class="collection section"><div class="collection-heading"><div><p class="eyebrow">${c.savedLabel}</p><h2>${c.savedTitle}</h2><p>${c.savedIntro}</p></div><div class="transfer"><button id="export">${c.export}</button><button id="import">${c.import}</button><input id="import-file" type="file" accept=".json,application/json" hidden><p>${c.importHint}</p></div></div><div id="saved-grid" class="saved-grid"></div><div class="comparison"><div class="comparison-heading"><h3>${c.compare}<span id="compare-count" class="mono">0 / 2</span></h3><button id="clear-compare">${c.clearCompare}</button></div><div id="comparison"></div></div><div class="limits"><span class="limits-mark" aria-hidden="true">R—01</span><div><h3>${c.limitsTitle}</h3><p>${c.limitsText}</p></div></div></section></main><footer class="footer"><a class="brand" href="#studio">RESON<span class="brand-dot" aria-hidden="true">◎</span></a><p>${c.footer}</p><a href="https://seoshiro.github.io/">${c.portfolio}</a><a href="https://github.com/seoshiro/reson-studio" target="_blank" rel="noopener noreferrer">${c.source}</a></footer>
  <dialog id="import-dialog" aria-labelledby="import-title"><form method="dialog"><h2 id="import-title">${c.importReview}</h2><div id="import-summary"></div><p>${c.importHint}</p><div class="dialog-actions"><button value="cancel">${c.cancel}</button><button class="primary" id="replace" value="confirm">${c.replace}</button></div></form></dialog><dialog id="remove-dialog" aria-labelledby="remove-title"><form method="dialog"><h2 id="remove-title">${c.deleteTitle}</h2><p id="remove-name"></p><p>${c.deleteText}</p><div class="dialog-actions"><button value="cancel">${c.cancel}</button><button id="confirm-remove" class="primary" value="confirm">${c.confirmRemove}</button></div></form></dialog>`;
  studio=new Viewer(q('#studio-visual'),current);anatomy=new Viewer(q('#anatomy-visual'),current,true);studio.motion=anatomy.motion=motion;
  for(const d of designs)if(!d.image)d.image=studio.capture(d.config);renderSaved();attach();updateScroll();
  if(recovered){status(c.storageRecovered,true);recovered=false;}
}
function attach(){
  document.querySelectorAll<HTMLButtonElement>('[data-option]').forEach(button=>button.addEventListener('click',()=>update({...current,[button.dataset.field!]:button.dataset.option})));
  for(const field of ['width','depth'] as const){q<HTMLInputElement>(`#${field}`).addEventListener('input',event=>{rangeStart??={...current};update({...current,[field]:Number((event.target as HTMLInputElement).value)},false);});q(`#${field}`).addEventListener('change',()=>{if(rangeStart&&!equal(rangeStart,current)){undo.push({current:rangeStart,designs:designs.map(d=>({...d,config:{...d.config}}))});if(undo.length>30)undo.shift();}rangeStart=null;sync();});}
  q('#undo').onclick=()=>{const old=undo.pop();if(!old)return;current=old.current;designs=old.designs;studio.setConfig(current);anatomy.setConfig(current);renderSaved();if(persist())status(copy[locale].undone);};
  q('#reset').onclick=()=>{update({...defaults});status(copy[locale].resetDone);};
  q<HTMLFormElement>('#save-form').onsubmit=event=>{event.preventDefault();const c=copy[locale];let name:string;try{name=cleanName(q<HTMLInputElement>('#design-name').value);if(designs.some(d=>d.name.toLocaleLowerCase()===name.toLocaleLowerCase()))throw Error('duplicate');}catch{status(c.nameError,true);q('#design-name').focus();return;}if(designs.length>=6){status(c.limit,true);return;}snapshot();designs.push({id:crypto.randomUUID(),name,config:{...current},image:studio.capture(current)});q<HTMLInputElement>('#design-name').value='';renderSaved();if(persist())status(c.saved);};
  q('#saved-grid').onclick=event=>{const button=(event.target as HTMLElement).closest<HTMLButtonElement>('button');if(!button)return;const d=designs.find(d=>d.id===(button.dataset.load||button.dataset.compare||button.dataset.remove));if(!d)return;
    if(button.dataset.load){update({...d.config});q('#studio').scrollIntoView({behavior:motion?'smooth':'instant'});status(copy[locale].loaded);}
    if(button.dataset.compare){selected=selected.includes(d.id)?selected.filter(id=>id!==d.id):[...selected.slice(-1),d.id];renderSaved();q<HTMLButtonElement>(`[data-compare="${d.id}"]`).focus();}
    if(button.dataset.remove){removeId=d.id;q('#remove-name').textContent=d.name;q<HTMLDialogElement>('#remove-dialog').showModal();}
  };
  q('#clear-compare').onclick=()=>{selected=[];renderSaved();};
  q<HTMLFormElement>('#remove-dialog form').onsubmit=event=>{event.preventDefault();const id=removeId;removeId=null;q<HTMLDialogElement>('#remove-dialog').close();if((event.submitter as HTMLButtonElement)?.value==='confirm'&&id){snapshot();designs=designs.filter(d=>d.id!==id);renderSaved();if(persist())status(copy[locale].removed);q('#export').focus();}};
  q<HTMLDialogElement>('#remove-dialog').oncancel=()=>{removeId=null;};
  q('#export').onclick=()=>{const blob=new Blob([exportDocument(current,designs)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='reson-designs.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status(copy[locale].exported);};
  q('#import').onclick=()=>{q<HTMLInputElement>('#import-file').value='';q<HTMLInputElement>('#import-file').click();};
  q<HTMLInputElement>('#import-file').onchange=async()=>{const file=q<HTMLInputElement>('#import-file').files?.[0];if(!file)return;const revision=++importVersion;try{if(file.size>30000)throw Error('size');const document=parseDocument(await file.text());if(revision!==importVersion)return;pending=document;q('#import-summary').innerHTML=`<p>${copy[locale][pending.current.finish]} · ${dimensions(pending.current)}</p><ul>${pending.designs.map(d=>`<li>${escape(d.name)}</li>`).join('')}</ul>`;q<HTMLDialogElement>('#import-dialog').showModal();}catch{if(revision!==importVersion)return;pending=null;status(copy[locale].invalid,true);}};
  q<HTMLFormElement>('#import-dialog form').onsubmit=event=>{event.preventDefault();const document=pending;pending=null;importVersion++;q<HTMLDialogElement>('#import-dialog').close();if((event.submitter as HTMLButtonElement)?.value==='confirm'&&document){snapshot();current=document.current;designs=document.designs.map(d=>({...d,id:crypto.randomUUID(),image:studio.capture(d.config)}));selected=[];studio.setConfig(current);anatomy.setConfig(current);renderSaved();if(persist())status(copy[locale].imported);}};
  q<HTMLDialogElement>('#import-dialog').oncancel=()=>{pending=null;importVersion++;};
  document.querySelectorAll<HTMLButtonElement>('[data-locale]').forEach(button=>button.onclick=()=>{if(button.dataset.locale===locale)return;const y=scrollY;studio.dispose();anatomy.dispose();locale=button.dataset.locale as Locale;try{localStorage.setItem('reson-language',locale);}catch{/* language remains usable */}const url=new URL(location.href);url.searchParams.set('lang',locale);history.replaceState(null,'',url);render();window.scrollTo({top:y,behavior:'instant'});q(`[data-locale="${locale}"]`).focus();});
  document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(button=>button.onclick=()=>{studio.setView(Number(button.dataset.view));document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));});
  q('#motion').onclick=()=>{motion=!motion;applyMotion();};
  const host=q('#studio-visual');let drag:{x:number;y:number;yaw:number;pitch:number}|null=null;
  host.onpointerdown=event=>{if(event.pointerType==='touch')return;drag={x:event.clientX,y:event.clientY,yaw:studio.targetYaw,pitch:studio.targetPitch};host.setPointerCapture(event.pointerId);host.focus();};
  host.onpointermove=event=>{if(drag)studio.setView(drag.yaw+(event.clientX-drag.x)*.009,drag.pitch+(event.clientY-drag.y)*.004);};host.onpointerup=host.onpointercancel=()=>{drag=null;};
  host.onkeydown=event=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home'].includes(event.key)){event.preventDefault();studio.setView(event.key==='Home'?-.4:studio.targetYaw+(event.key==='ArrowLeft'?-.2:event.key==='ArrowRight'?.2:0),event.key==='Home'?.055:studio.targetPitch+(event.key==='ArrowUp'?-.04:event.key==='ArrowDown'?.04:0));}};
  document.querySelectorAll<HTMLButtonElement>('[data-chapter]').forEach(button=>button.onclick=()=>{const p=[0,.32,.64,1][Number(button.dataset.chapter)],r=q('#scroll-study').getBoundingClientRect(),range=Math.max(1,r.height-innerHeight);window.scrollTo({top:scrollY+r.top+range*p,behavior:motion?'smooth':'instant'});if(!motion){manualAmount=Number(button.dataset.chapter)===0||Number(button.dataset.chapter)===3?0:1;anatomy.setAmount(manualAmount);q<HTMLInputElement>('#explore').value=String(manualAmount*100);}});
  q<HTMLInputElement>('#explore').oninput=event=>{manualAmount=Number((event.target as HTMLInputElement).value)/100;anatomy.setAmount(manualAmount);};
}
function applyMotion(){studio.motion=anatomy.motion=motion;document.documentElement.classList.toggle('motion-off',!motion);q('#motion').textContent=`${copy[locale].motion}: ${motion?copy[locale].motionOn:copy[locale].motionOff}`;q('#motion').setAttribute('aria-pressed',String(motion));if(!motion){manualAmount=0;q<HTMLInputElement>('#explore').value='0';anatomy.setAmount(0);}updateScroll();studio.invalidate();}
function updateScroll(){scrollFrame=0;if(!anatomy)return;const r=q('#scroll-study').getBoundingClientRect(),range=Math.max(1,r.height-innerHeight);progress=Math.max(0,Math.min(1,-r.top/range));const chapter=progress<.15?0:progress<.47?1:progress<.82?2:3,c=copy[locale];q('#chapter-title').textContent=c.chapters[chapter];q('#chapter-text').textContent=c.chapterText[chapter];q('.chapter-number').textContent=`0${chapter+1} / 04`;document.querySelectorAll<HTMLButtonElement>('[data-chapter]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.chapter)===chapter)));q<HTMLElement>('.scroll-line i').style.width=`${progress*100}%`;if(motion){anatomy.setAmount(explosion(progress));anatomy.setView(-.40-progress*.36,.055);q<HTMLInputElement>('#explore').value=String(Math.round(explosion(progress)*100));}}
window.addEventListener('scroll',()=>{if(!scrollFrame)scrollFrame=requestAnimationFrame(updateScroll);},{passive:true});window.addEventListener('resize',updateScroll);media.addEventListener('change',()=>{motion=!media.matches;applyMotion();});
render();applyMotion();
const textSize=new ResizeObserver(()=>document.documentElement.classList.toggle('text-enlarged',parseFloat(getComputedStyle(document.documentElement).fontSize)>20));textSize.observe(document.documentElement);
declare global {interface Window {__RESON:{state:()=>unknown}}}
window.__RESON={state:()=>({locale,current,designs:designs.map(d=>({id:d.id,name:d.name,config:d.config,hasImage:!!d.image})),undo:undo.length,progress,motion,studio:studio.diagnostics(),anatomy:anatomy.diagnostics(),scroll:{start:scrollY+q('#scroll-study').getBoundingClientRect().top,range:q('#scroll-study').clientHeight-innerHeight}})};
